#!/bin/bash
quoted=$(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | awk 'BEGIN {
FS = "\n" } { printf "\"%s\" ", $1 }' | sed -e s#\"\"##)
#eval "your-program $quoted"

eval "python3 /path/to/imagemash.py $quoted"


#xterm -hold -e "python3 /path/to/imagemash.py $quoted"